# Constants

"""

QPSK_AMPLITUDE
PREAMBLE_LENGTH
ENERGY_MAX
...

"""

# === PRÉAMBULE ===
PREAMBLE_AMPLITUDE = 3.0
PREAMBLE_LENGTH = 4
 
# === MODULATION QPSK ===
ENERGY_PER_QPSK_SYMBOL = 1.5
QPSK_AMPLITUDE = (ENERGY_PER_QPSK_SYMBOL / 2) ** 0.5
 
# === HADAMARD ===
HADAMARD_INFO_BITS = 4
HADAMARD_CODED_BITS = 8
HADAMARD_M = 3
 
# === CONTRAINTES ===
N_MAX = 500
ENERGY_MAX = 1200
SIGMA = 1.0
N_INFO_BITS = 240
N_CHARS = 40
BITS_PER_CHAR = 6
 
# === ALPHABET ===
ALPHABET = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 .'
